steps:
- name: gcr.io/cloud-builders/git
  args: ['clone', '--recurse-submodules', 'https://github.com/${_REPO_OWNER}/${_APP_NAME}']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_APP_NAME}:$SHORT_SHA', '${_APP_NAME}/.']
- name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/$PROJECT_ID/${_APP_NAME}:$SHORT_SHA']
- name: gcr.io/cloud-builders/kubectl
  args: ['apply', '-f', 'k8s/']
substitutions:
    _APP_NAME: myblog
    _REPO_OWNER: mathieu-benoit
    _CLOUDSDK_COMPUTE_ZONE: us-east1-b
    _CLOUDSDK_CONTAINER_CLUSTER: mygkecluster
    _CLOUDSDK_CORE_PROJECT: myblog
