steps:
- name: gcr.io/cloud-builders/git
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cd myblog
    git submodule init
    git submodule update
- name: gcr.io/cloud-builders/docker
  args: ["build", "-t", "gcr.io/$PROJECT_ID/myblog:$COMMIT_SHA", "."]
- name: gcr.io/cloud-builders/docker
  args: ["push", "gcr.io/$PROJECT_ID/myblog:$COMMIT_SHA"]
