steps:
- name: gcr.io/cloud-builders/git
  args: ['submodule', 'update', '--init', '--recursive']
- name: gcr.io/cloud-builders/docker
  args: ["build", "-t", "gcr.io/$PROJECT_ID/myblog:$COMMIT_SHA", "."]
- name: gcr.io/cloud-builders/docker
  args: ["push", "gcr.io/$PROJECT_ID/myblog:$COMMIT_SHA"]
