steps:
- name: gcr.io/cloud-builders/git
  args: ['clone', '--recurse-submodules', '$_REPO_URL']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/myblog:$SHORT_SHA', 'myblog/.']
- name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/$PROJECT_ID/myblog:$SHORT_SHA']
