baseurl = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5
defaultContentLanguage = "en"

[params]
  contentTypeName = "posts"
  defaultTheme = "dark"
  showMenuItems = 2
  showReadingTime = false
  description = "Mathieu Benoit's blog"
  logoText = "always up, always on"
  logoHomeLink = "/"

[languages]
  [languages.en]
    title = "always up, always on"
    menuMore = "show more"
    readMore = "read more"
    newerPosts = "newer posts"
    olderPosts = "older posts"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "about"
        url = "/about/"
        weight = "30"
  [languages.fr]
    title = "always up, always on"
    menuMore = "voir plus"
    readMore = "lire plus"
    newerPosts = "plus récents"
    olderPosts = "moins récents"

    [languages.fr.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "à propos"
        url = "/about/"
        weight = "30"
