baseurl = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5
enableEmoji = true

[params]
  contentTypeName = "posts"
  defaultTheme = "dark"
  showMenuItems = 2
  showReadingTime = false
  description = "Mathieu Benoit's blog"

[languages]
  [languages.en]
    title = "always up, always on"
    menuMore = "show more"
    readMore = "read more"
    newerPosts = "newer posts"
    olderPosts = "older posts"

    [languages.en.params.logo]
      logoText = "always up, always on"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "about"
        url = "/about/"
        weight = "30"
