apiVersion: apps/v1
kind: Deployment
metadata:
  name: myblog
  labels:
    app.kubernetes.io/name: myblog
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: myblog
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myblog
    spec:
      serviceAccountName: default
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
      containers:
        - name: myblog
          securityContext:
            capabilities:
              drop:
                - all
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          image: CONTAINER_IMAGE_NAME
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              port: 8080
              path: /
          livenessProbe:
            httpGet:
              port: 8080
              path: /
          volumeMounts:
          - mountPath: /tmp
            name: tmp
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
      - emptyDir: {}
        name: tmp
