apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: myblog
  annotations:
    kubernetes.io/ingress.global-static-ip-name: myblog-static-ip
    networking.gke.io/managed-certificates: myblog
    cloud.google.com/neg: '{"ingress": true}'
spec:
  backend:
    serviceName: myblog
    servicePort: 8080
