baseurl = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[params]
  contentTypeName = "posts"
  defaultTheme = "dark"
  showMenuItems = 2
  showReadingTime = false
  description = "Mathieu Benoit's blog"

[languages]
  [languages.en]
    title = "always up, always on"

    [languages.en.params.logo]
      logoText = "always up, always on"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "about"
        url = "/about"
        weight = "30"
